const actions = {
  FETCH_ORGANIZATIONS: "FETCH_ORGANIZATIONS",
  FETCH_ORGANIZATIONS_SUCCESS: "FETCH_ORGANIZATIONS_SUCCESS",
  FETCH_ORGANIZATIONS_FAILURE: "FETCH_ORGANIZATIONS_FAILURE",
};

export default actions;
