const actions = {
  FETCH_PROPERTIES: "FETCH_PROPERTIES",
  FETCH_PROPERTIES_SUCCESS: "FETCH_PROPERTIES_SUCCESS",
  FETCH_PROPERTIES_FAILURE: "FETCH_PROPERTIES_FAILURE",

  FETCH_PROPERTY: "FETCH_PROPERTY",
  FETCH_PROPERTY_SUCCESS: "FETCH_PROPERTY_SUCCESS",
  FETCH_PROPERTY_FAILURE: "FETCH_PROPERTY_FAILURE",
};

export default actions;
