export const properties = [
  {
    id: 1,
    property: "Gabels Gate 19, 0272 Oslo",
    open: 2,
    ongoing: 4,
    expired: 2,
    solved: 5,
    progress: 70,
  },
  {
    id: 2,
    property: "Thereses Gate 19, 0124 Oslo",
    open: 2,
    ongoing: 4,
    expired: 2,
    solved: 5,
    progress: 10,
  },
  {
    id: 3,
    property: "Oreliveien 8, 0580 Oslo",
    open: 2,
    ongoing: 4,
    expired: 2,
    solved: 5,
    progress: 45,
  },
  {
    id: 4,
    property: "Tjuvholmen Alle 4, 0160 Oslo",
    open: 2,
    ongoing: 4,
    expired: 2,
    solved: 5,
    progress: 100,
  },
  {
    id: 5,
    property: "Ekebergsletta, 0540 Oslo",
    open: 2,
    ongoing: 4,
    expired: 2,
    solved: 5,
    progress: 70,
  },
  {
    id: 6,
    property: "Oreliveien 50, 0220 Oslo",
    open: 0,
    ongoing: 0,
    expired: 0,
    solved: 0,
    progress: 0,
  },
  {
    id: 7,
    property: "Bogstadveien 2, 0110 Oslo",
    open: 0,
    ongoing: 0,
    expired: 0,
    solved: 0,
    progress: 0,
  },
  {
    id: 8,
    property: "Kongens gate 1, 0112 Oslo",
    open: 0,
    ongoing: 0,
    expired: 0,
    solved: 0,
    progress: 0,
  },
];
