export const tasks = [
  {
    id: 1,
    title: "Egenkontroll brannvern",
    date: "14.05.2023",
    owner: "David Gulbrandsen",
    property: "Gabels Gate 19, 0272 Oslo",
    status: "Solved",
  },
  {
    id: 2,
    title: "Egenkontroll heis",
    date: "14.05.2023",
    owner: "David Gulbrandsen",
    property: "Gabels Gate 19, 0272 Oslo",
    status: "Expired",
  },
  {
    id: 3,
    title: "arlig kontroll slokkeutstyr",
    date: "14.05.2023",
    owner: "David Gulbrandsen",
    property: "Gabels Gate 19, 0272 Oslo",
    status: "InProgress",
  },
  {
    id: 4,
    title: "Egenkontroll sluker",
    date: "14.05.2023",
    owner: "David Gulbrandsen",
    property: "Gabels Gate 19, 0272 Oslo",
    status: "Open",
  },
  {
    id: 5,
    title: "Egenkontroll heis",
    date: "14.05.2023",
    owner: "David Gulbrandsen",
    property: "Gabels Gate 19, 0272 Oslo",
    status: "Expired",
  },
  {
    id: 6,
    title: "arlig kontroll slokkeutstyr",
    date: "14.05.2023",
    owner: "David Gulbrandsen",
    property: "Gabels Gate 19, 0272 Oslo",
    status: "InProgress",
  },
  {
    id: 7,
    title: "Egenkontroll sluker",
    date: "14.05.2023",
    owner: "David Gulbrandsen",
    property: "Gabels Gate 19, 0272 Oslo",
    status: "Open",
  },
  {
    id: 8,
    title: "Egenkontroll sluker",
    date: "14.05.2023",
    owner: "David Gulbrandsen",
    property: "Gabels Gate 19, 0272 Oslo",
    status: "Open",
  },
];
